"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const FoodMenuModel_1 = require("./FoodMenuModel");
const RestaurantModel_1 = require("./RestaurantModel");
exports.FoodMenusData = [
    new FoodMenuModel_1.FoodMenuModel("Martabak Beng2 Tiker (Tipis Kering)", "Beng2 + Keju + Susu", 25000, new RestaurantModel_1.RestaurantModel("Martabak Gahar", "Panglima Polim", "JL. Panglima Polim 5 No. 4")),
    new FoodMenuModel_1.FoodMenuModel("Martabak Seafood Special", "Perpaduan antara Cumi + Udang + Kepiting", 65000, new RestaurantModel_1.RestaurantModel("Martabak Gahar", "Panglima Polim", "JL. Panglima Polim 5 No. 4")),
    new FoodMenuModel_1.FoodMenuModel("Martabak Beng2 (Special)", "Beng2 + Keju + Susu", 35000, new RestaurantModel_1.RestaurantModel("Martabak Gahar", "Panglima Polim", "JL. Panglima Polim 5 No. 4")),
    new FoodMenuModel_1.FoodMenuModel("Martabak Rendang Spesial", "Perpaduan cita rasa daging rendang khas minang", 65000, new RestaurantModel_1.RestaurantModel("Martabak Gahar", "Panglima Polim", "JL. Panglima Polim 5 No. 4")),
    new FoodMenuModel_1.FoodMenuModel("Martabak Thailand Style (Special Gahar)", "Pisang + Milo + Susu", 65000, new RestaurantModel_1.RestaurantModel("Martabak Gahar", "Panglima Polim", "JL. Panglima Polim 5 No. 4")),
    new FoodMenuModel_1.FoodMenuModel("Martabak Daging Gokil", "Daging Gokil", 82500, new RestaurantModel_1.RestaurantModel("Matabak BOSS", "Pangpol IX", "JL. Panglima Polim 3 No. 1-3, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Besar Paket Toblerone", "Keju + Toblerone + Kacang", 112000, new RestaurantModel_1.RestaurantModel("Matabak BOSS", "Pangpol IX", "JL. Panglima Polim 3 No. 1-3, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Besar Paket Ovo Keju", "Ovaltine + Keju + Kacang", 145000, new RestaurantModel_1.RestaurantModel("Matabak BOSS", "Pangpol IX", "JL. Panglima Polim 3 No. 1-3, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Besar Paket Real Boss", "Keju + Boss Choco Spread + Kacang", 85000, new RestaurantModel_1.RestaurantModel("Matabak BOSS", "Pangpol IX", "JL. Panglima Polim 3 No. 1-3, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Classic Telor Daging Sapi", "", 85000, new RestaurantModel_1.RestaurantModel("BANG!Martabak", "Panglima Polim", "JL. Panglima Polim Raya No. 102")),
    new FoodMenuModel_1.FoodMenuModel("Rock Nutella", "", 95000, new RestaurantModel_1.RestaurantModel("BANG!Martabak", "Panglima Polim", "JL. Panglima Polim Raya No. 102")),
    new FoodMenuModel_1.FoodMenuModel("Classic Telor Kepiting", "", 100000, new RestaurantModel_1.RestaurantModel("BANG!Martabak", "Panglima Polim", "JL. Panglima Polim Raya No. 102")),
    new FoodMenuModel_1.FoodMenuModel("Classic Manis Coklat", "", 60000, new RestaurantModel_1.RestaurantModel("BANG!Martabak", "Panglima Polim", "JL. Panglima Polim Raya No. 102")),
    new FoodMenuModel_1.FoodMenuModel("Classic Manis Keju", "", 65000, new RestaurantModel_1.RestaurantModel("BANG!Martabak", "Panglima Polim", "JL. Panglima Polim Raya No. 102")),
    new FoodMenuModel_1.FoodMenuModel("Aneka Nasi Lemak Ayam", "", 30000, new RestaurantModel_1.RestaurantModel("Nasi Lemak Lontong Medan", "Melawai", "Pasaraya Grande, Food Court @Dapur Raya, JL. Iskandarsyah, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Goreng Kambing 1 Porsi", "", 39000, new RestaurantModel_1.RestaurantModel("Nasi Goreng Kambing Kebon Sirih", "Melawai", "Pasaraya Blok M, Foodcourt Dapuraya Basement, JL. Iskandarsyah Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Sate Padang", "", 29700, new RestaurantModel_1.RestaurantModel("Sederhana SA", "Melawai", "JL. Melawai 4 No. B6-7, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Soto Padang", "", 23100, new RestaurantModel_1.RestaurantModel("Sederhana SA", "Melawai", "JL. Melawai 4 No. B6-7, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Ayam Pop", "", 19800, new RestaurantModel_1.RestaurantModel("Sederhana SA", "Melawai", "JL. Melawai 4 No. B6-7, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Rendang Daging", "", 19800, new RestaurantModel_1.RestaurantModel("Sederhana SA", "Melawai", "JL. Melawai 4 No. B6-7, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Gulai Kikil/Tunjang", "", 19800, new RestaurantModel_1.RestaurantModel("Sederhana SA", "Melawai", "JL. Melawai 4 No. B6-7, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Sate Surjan", "", 21000, new RestaurantModel_1.RestaurantModel("Gudeg Mbok Menco", "Melawai", "Blok M Square, Pujasera, Lantai Basement, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Gudeg Manis/Mercon Endog (Telor)", "", 24000, new RestaurantModel_1.RestaurantModel("Gudeg Mbok Menco", "Melawai", "Blok M Square, Pujasera, Lantai Basement, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Gudeg Manis/Mercon Paha/Sayap Ayam", "", 29000, new RestaurantModel_1.RestaurantModel("Gudeg Mbok Menco", "Melawai", "Blok M Square, Pujasera, Lantai Basement, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Oseng-Oseng Mercon", "", 25000, new RestaurantModel_1.RestaurantModel("Gudeg Mbok Menco", "Melawai", "Blok M Square, Pujasera, Lantai Basement, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Megono Komplit", "", 25000, new RestaurantModel_1.RestaurantModel("Gudeg Mbok Menco", "Melawai", "Blok M Square, Pujasera, Lantai Basement, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Es Teler (Reguler)", "", 30000, new RestaurantModel_1.RestaurantModel("Es Teler 77", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Nasi + Ayam Goreng Kremes + Es Teh Manis", "", 30000, new RestaurantModel_1.RestaurantModel("Es Teler 77", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Otak-Otak (5 Pcs)", "", 28000, new RestaurantModel_1.RestaurantModel("Es Teler 77", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Mie Ayam Pedas Istimewa + Es Teh Manis", "", 35000, new RestaurantModel_1.RestaurantModel("Es Teler 77", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Mie Aceh Tumis Daging", "", 30000, new RestaurantModel_1.RestaurantModel("Mie Aceh Blok M", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Gurih Aceh Kambing", "", 36000, new RestaurantModel_1.RestaurantModel("Mie Aceh Blok M", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Roti Cane Susu Keju", "", 24000, new RestaurantModel_1.RestaurantModel("Mie Aceh Blok M", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Goreng Kambing", "", 24000, new RestaurantModel_1.RestaurantModel("Mie Aceh Blok M", "Melawai", "Blok M Square, Pujasera, Lantai 5, JL. Melawai Raya, Melawai, Jakarta")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Bakar Ayam Rica", "", 33000, new RestaurantModel_1.RestaurantModel("Warung Lombok", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Combo B (Ayam Bakar Dada/Paha)", "", 33000, new RestaurantModel_1.RestaurantModel("Warung Lombok", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bubur Ayam Biasa", "", 20000, new RestaurantModel_1.RestaurantModel("Apjay Bubur Ayam", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bubur Ayam Ati Ampela", "", 26000, new RestaurantModel_1.RestaurantModel("Apjay Bubur Ayam", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bubur Ayam Keju", "", 25000, new RestaurantModel_1.RestaurantModel("Apjay Bubur Ayam", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bubur Ayam Ati Ampela + Telor", "", 29000, new RestaurantModel_1.RestaurantModel("Apjay Bubur Ayam", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bubur Ayam Spesial", "", 33000, new RestaurantModel_1.RestaurantModel("Apjay Bubur Ayam", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Wagyu", "", 117000, new RestaurantModel_1.RestaurantModel("Bento Steak.co", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Prime Chicken Steak", "", 37000, new RestaurantModel_1.RestaurantModel("Bento Steak.co", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Wagyu Black Angus A", "", 110000, new RestaurantModel_1.RestaurantModel("Bento Steak.co", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Chicken Crispy Steak", "", 27000, new RestaurantModel_1.RestaurantModel("Bento Steak.co", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Reguler Sirlon / Tender Steak", "", 48000, new RestaurantModel_1.RestaurantModel("Bento Steak.co", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bebek Dower Saos Telor Asin", "", 44000, new RestaurantModel_1.RestaurantModel("Bento Dower", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Bebek Mandala", "", 35000, new RestaurantModel_1.RestaurantModel("Nasi Bebek Mandala", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Tahu Tek", "", 20000, new RestaurantModel_1.RestaurantModel("Tahu Telor Ngalam", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Pempek Kapal Selam", "", 25000, new RestaurantModel_1.RestaurantModel("Pempek Palembang Seorang Sahabat", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Pempek Kecil Goreng", "", 8500, new RestaurantModel_1.RestaurantModel("Pempek Palembang Seorang Sahabat", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Tekwan", "", 8500, new RestaurantModel_1.RestaurantModel("Pempek Palembang Seorang Sahabat", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Spaghetti Aglio Olio", "", 40000, new RestaurantModel_1.RestaurantModel("KLM Bistro", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Fetuccine Alfredo", "", 40000, new RestaurantModel_1.RestaurantModel("KLM Bistro", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Cumi Cabe Hijau", "", 40000, new RestaurantModel_1.RestaurantModel("KLM Bistro", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Nasi Sapi Lada Hitam", "", 40000, new RestaurantModel_1.RestaurantModel("KLM Bistro", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Fish & Chips", "", 60000, new RestaurantModel_1.RestaurantModel("KLM Bistro", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bakso Asmara", "", 17000, new RestaurantModel_1.RestaurantModel("Bakso Cinta Mampang", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bakso Cemburu", "", 17000, new RestaurantModel_1.RestaurantModel("Bakso Cinta Mampang", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Bakso Rindu", "", 17000, new RestaurantModel_1.RestaurantModel("Bakso Cinta Mampang", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Taro Pizza Reguler", "", 47000, new RestaurantModel_1.RestaurantModel("Pizza Nagih", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Wagyu Pizza Reguler", "", 47000, new RestaurantModel_1.RestaurantModel("Pizza Nagih", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Creamy Scallop Pizza Reguler", "", 47000, new RestaurantModel_1.RestaurantModel("Pizza Nagih", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Samosa", "", 38000, new RestaurantModel_1.RestaurantModel("Ganesha Ek Sanskriti", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Murg Tikka (Chicken Tikka)", "", 88000, new RestaurantModel_1.RestaurantModel("Ganesha Ek Sanskriti", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Napolina", "", 115000, new RestaurantModel_1.RestaurantModel("Eastern Promise", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Boneless Gren Chicken Tikka", "", 105000, new RestaurantModel_1.RestaurantModel("Eastern Promise", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Chicken Tikka Masala", "", 105000, new RestaurantModel_1.RestaurantModel("Eastern Promise", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Roast Portk", "", 155000, new RestaurantModel_1.RestaurantModel("Eastern Promise", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Butter Naan", "", 39000, new RestaurantModel_1.RestaurantModel("Go! Curry", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Cilantro Butter Rice with Chicken Katsu + Brown Curry", "", 85000, new RestaurantModel_1.RestaurantModel("Go! Curry", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Lamb (regular)", "", 155000, new RestaurantModel_1.RestaurantModel("Go! Curry", "Blok M", "Plaza Blok M, Lantai 6")),
    new FoodMenuModel_1.FoodMenuModel("Cheese Naan", "", 45000, new RestaurantModel_1.RestaurantModel("Go! Curry", "Blok M", "Plaza Blok M, Lantai 6")),
];
